# 1. ベースイメージ
FROM node:23-alpine

# 3. 作業ディレクトリを作成
WORKDIR /app

# 4. package.json と package-lock.json をコピー（キャッシュを最大化）
COPY package.json package-lock.json ./

# 5. 依存関係をインストール
RUN npm install

# 6. 残りのアプリのソースコードをコピー
COPY . .

# 7. Next.js のデフォルトポートを公開
EXPOSE 3000

# 9. Next.js の開発サーバーを起動
CMD ["npm", "run", "dev"]

